---
# tasks file for net_operations
- name: validate we have everything to analyze results
  validate_role_spec:
      spec: flow_analysis_spec.yaml

- name: Analyze flow sent and received
  flow_analysis:
    flows_sent: "{{ generated_flow_file }}"
    flows_received: "{{ sink_path_flow_output }}"
    wildcard_host: "{{ tgn_wildcard_dest }}"
  register: results

- name: Print the results
  debug: msg="{{ results }}"
