---
# tasks file for net_operations
- name: validate we have everything to configure packet capture device
  validate_role_spec:
    spec: pre_config_sink_device_spec.yaml

- name: Invoke provider role to configure device before start of packet capture
  include_role:
    name: "{{ ansible_network_provider }}"
    tasks_from: net_operations/pre_config_sink_device
