---
# tasks file for net_operations
- name: validate role spec
  validate_role_spec:
    spec: parse_validate_acl_spec.yaml

- name: invoke network provider
  include_role:
    name: "{{ ansible_network_provider }}"
    tasks_from: net_operations/parse_validate_acl
