---
# tasks file for net_operations
- name: "Include dut playbook"
  include_tasks: dut.yml
  when: device_role == 'dut'

- name: "configure sink device before starting traffic"
  include_tasks: config_sink.yml
  when: device_role == 'sink' and stage == 'pre_config'

- name: "Include traffic source device playbook"
  include_tasks: source.yml
  when: device_role == 'source'

- name: "Include traffic sink device playbook"
  include_tasks: sink.yml
  when: device_role == 'sink' and stage == 'post_traffic'

- name: "Analyze results"
  include_tasks: analyze.yml
  when: device_role == 'analyzer'
