---
# tasks file for net_operations
- name: "Include dut playbook"
  include_tasks: dut.yml
  when: device_role == 'dut'

- name: "Include traffic source device playbook"
  include_tasks: source.yml
  when: device_role == 'source'

- name: "Include traffic sink device platbook"
  include_tasks: sink.yml
  when: device_role == 'sink'
