---
# tasks file for net_operations
- name: "check for required fact: "
  fail:
    msg: "Missing required fact: service id "
  when: not net_operation.services

- name: include device role specific tasks
  include_tasks: "{{ item }}"
  with_first_found:
    - files:
        - generate_packet_dict.yml
      paths:
        - "{{ playbook_dir }}/providers/{{ ansible_network_os }}"
        - "{{ role_path }}/providers/{{ ansible_network_os }}"
