---
# tasks file for net_operations
#
- name: validate we have everything to parse captured packets
  validate_role_spec:
    spec: packet_capture_logs_spec.yaml

- name: Invoke provider role to parse captured packets
  include_role:
    name: "{{ ansible_network_provider }}"
    tasks_from: net_operations/sink_packet_capture_logs
