---
# tasks file for net_operations
- name: validate we have everything to send packets
  validate_role_spec:
    spec: packets_send_spec.yaml

- name: Invoke provider role to send packets
  include_role:
    name: "{{ ansible_network_provider }}"
    tasks_from: packets_send
